# Simple job to run custom script
executable = message.sh
arguments = $(JOB) $(ClusterId) $(Process) $(my_message)

log = log/job.log
output = out/job.$(JOB).$(Process).out
error = err/job.$(JOB).$(Process).err

message_output_file = message.$(JOB).$(Process).txt
transfer_output_files = $(message_output_file)
transfer_output_remaps = "$(message_output_file) = output_messages/$(message_output_file)"

request_cpus = 1
request_memory = 1GB
request_disk = 1GB

queue 2

